# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  package_version: 'x.y.z'    

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install dependency from package.json'

- script: |
    package_version=$(node -p "require('./package.json').version")
    echo "The value of the global variable package_version=$package_version"
  displayName: 'node exec --> show $package_version'

- script: |
    npm pack
  displayName: 'Package for npm release (generates .tgz file)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'


# Release
- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    archiveFilePatterns: '*.tgz'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/npm-publish'

- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: publish
    workingDir: '$(Build.ArtifactStagingDirectory)/npm-publish/package'
    verbose: false
    publishEndpoint: 'npm-registry-jalalhejazi'

